<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>T3MPTestDriver</AssemblyName>
    <RootNamespace>T3MPTestDriver</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Timberborn.EntitySystem">
      <HintPath>$(TimberbornManagedDir)\Timberborn.EntitySystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.BaseComponentSystem">
      <HintPath>$(TimberbornManagedDir)\Timberborn.BaseComponentSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.Common">
      <HintPath>$(TimberbornManagedDir)\Timberborn.Common.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Bindito.Core">
      <HintPath>$(TimberbornManagedDir)\Bindito.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.GameSaveRepositorySystem">
      <HintPath>$(TimberbornManagedDir)\Timberborn.GameSaveRepositorySystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.GameSceneLoading">
      <HintPath>$(TimberbornManagedDir)\Timberborn.GameSceneLoading.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.MapRepositorySystem">
      <HintPath>$(TimberbornManagedDir)\Timberborn.MapRepositorySystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.ModManagerScene">
      <HintPath>$(TimberbornManagedDir)\Timberborn.ModManagerScene.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.SingletonSystem">
      <HintPath>$(TimberbornManagedDir)\Timberborn.SingletonSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.TimeSystem">
      <HintPath>$(TimberbornManagedDir)\Timberborn.TimeSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(TimberbornManagedDir)\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
