<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="runtime/**/*.cs" />
    <PackageReference Include="Mono.Cecil" Version="0.11.6" />
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(TimberbornManagedDir)\UnityEngine.CoreModule.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
