[CmdletBinding()]
param(
    [string] $Configuration = 'Release',
    [string] $ModsPath = (Join-Path $env:USERPROFILE 'Documents\Timberborn\Mods'),
    [string] $ModFolderName = 'T3MP',
    # Benchmark-only: copies benchmark\AssetBundles into the deployed mod so
    # BotInstancingProbe can load its shader bundle. Never use before a
    # Workshop upload — the bundle only loads on the game version whose Unity
    # built it and crashes the mod loader on any other version.
    [switch] $IncludeBenchmarkBundles
)

$ErrorActionPreference = 'Stop'

$repoRoot = Resolve-Path -LiteralPath (Join-Path $PSScriptRoot '..')
$projectPath = Join-Path $repoRoot.Path 'src\T3MP\T3MP.csproj'
$modSourcePath = Join-Path $repoRoot.Path 'mod'
$targetPath = Join-Path $ModsPath $ModFolderName

if (-not (Test-Path -LiteralPath $ModsPath)) {
    throw "Timberborn Mods folder was not found: $ModsPath"
}

dotnet build $projectPath -c $Configuration
if ($LASTEXITCODE -ne 0) {
    throw "dotnet build failed with exit code $LASTEXITCODE"
}

$builtDll = Join-Path (Split-Path -Parent $projectPath) "bin\$Configuration\netstandard2.1\Code.dll"
if (-not (Test-Path -LiteralPath $builtDll)) {
    throw "Built DLL was not found: $builtDll"
}

$resolvedModsPath = (Resolve-Path -LiteralPath $ModsPath).Path.TrimEnd('\')
$workshopDataBackup = $null
if (Test-Path -LiteralPath $targetPath) {
    $resolvedTargetPath = (Resolve-Path -LiteralPath $targetPath).Path
    if (-not $resolvedTargetPath.StartsWith($resolvedModsPath, [System.StringComparison]::OrdinalIgnoreCase)) {
        throw "Refusing to clean target outside Mods folder: $resolvedTargetPath"
    }
    # workshop_data.json is generated by the in-game Steam uploader and ties
    # this folder to the existing Workshop item. Losing it turns the next
    # upload into a NEW listing, so always carry it across the clean.
    $workshopDataPath = Join-Path $resolvedTargetPath 'workshop_data.json'
    if (Test-Path -LiteralPath $workshopDataPath) {
        $workshopDataBackup = [System.IO.File]::ReadAllBytes($workshopDataPath)
    }
    Remove-Item -LiteralPath $resolvedTargetPath -Recurse -Force
}

New-Item -ItemType Directory -Force -Path $targetPath | Out-Null
Copy-Item -Path (Join-Path $modSourcePath '*') -Destination $targetPath -Recurse -Force
Copy-Item -LiteralPath $builtDll -Destination (Join-Path $targetPath 'Code.dll') -Force
if ($IncludeBenchmarkBundles) {
    $benchmarkBundles = Join-Path $repoRoot.Path 'benchmark\AssetBundles'
    if (-not (Test-Path -LiteralPath $benchmarkBundles)) {
        throw "Benchmark AssetBundles folder was not found: $benchmarkBundles"
    }
    Copy-Item -LiteralPath $benchmarkBundles -Destination (Join-Path $targetPath 'AssetBundles') -Recurse -Force
    Write-Warning 'Benchmark AssetBundles included - do NOT upload this build to the Workshop.'
}
if ($null -ne $workshopDataBackup) {
    [System.IO.File]::WriteAllBytes((Join-Path $targetPath 'workshop_data.json'), $workshopDataBackup)
}

Write-Host "Deployed to: $targetPath"

